name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Run tests
        run: deno test -A ./example
      - name: Check if workerdManager.node.generated.ts is up-to-date
        run: |
          cp ./runtimes/workerdManager.generated.ts ./runtimes/workerdManager.generated.ts.bak
          deno task generateWorkerdManager
          diff ./runtimes/workerdManager.generated.ts ./runtimes/workerdManager.generated.ts.bak
          rm ./runtimes/workerdManager.generated.ts.bak
      - name: Run tests
        run: deno publish
