name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/cross-test/workerd-manager
          key: ${{ runner.os }}-cross-test-workerd-manager
      - name: Run tests
        run: deno test -A ./example
      - name: Check if workerdManager.node.generated.ts is up-to-date
        run: |
          cp ./runtimes/workerdManager.generated.ts ./runtimes/workerdManager.generated.ts.bak
          deno task generateWorkerdManager
          diff ./runtimes/workerdManager.generated.ts ./runtimes/workerdManager.generated.ts.bak
      - name: Run tests
        run: deno publish
